### ISSUE TITLE
Shelf is empty again after reload of page

### ISSUE THREAD

**Issue by aschrijver** [Alamantus/little-library#1]
Nice project. I uploaded an ebook and provided author, details, etc. But after reloading the page the shelf is empty again, and there is no history or entries of other people.

Maybe i do not understand the functionaltiy properly, or you are not saving entries yet, or there is a review process before book entries appear, or there is a bug to fix?

**Comment by Alamantus** [comment]
It appears that I should have done more research into Heroku before choosing it as to host the flagship instance. I thought that static files were only cleared when the project was re-deployed, but it apparently also randomly restarts the servers, clearing the files: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

I will look into either a solution from Heroku or find some better host and report back.

**Comment by Alamantus** [comment]
I have moved the flagship site to a VM on Google Cloud, which has a persistent file system. The new URL is http://library.quietplace.tk and the old Heroku URL redirects to it.
